/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const RoutineLog = IDL.Record({
  'date' : IDL.Text,
  'completed' : IDL.Bool,
  'routineId' : IDL.Nat,
});
export const DailySummary = IDL.Record({
  'movement' : IDL.Bool,
  'stress' : IDL.Bool,
  'routines' : IDL.Bool,
  'sleep' : IDL.Bool,
  'fasting' : IDL.Bool,
  'nutrition' : IDL.Bool,
});
export const MovementEntry = IDL.Record({
  'id' : IDL.Nat,
  'activityType' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'intensity' : IDL.Nat,
});
export const NutritionEntry = IDL.Record({
  'id' : IDL.Nat,
  'fat' : IDL.Nat,
  'carbs' : IDL.Nat,
  'calories' : IDL.Nat,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'protein' : IDL.Nat,
});
export const SleepEntry = IDL.Record({
  'id' : IDL.Nat,
  'durationHours' : IDL.Float64,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'qualityRating' : IDL.Nat,
});
export const StressEntry = IDL.Record({
  'id' : IDL.Nat,
  'techniques' : IDL.Text,
  'level' : IDL.Nat,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMovementEntry' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addNutritionEntry' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addRoutine' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'addSleepEntry' : IDL.Func([IDL.Float64, IDL.Nat, IDL.Text], [IDL.Nat], []),
  'addStressEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyScore' : IDL.Func([], [IDL.Nat], ['query']),
  'getTodayRoutineLogs' : IDL.Func([], [IDL.Vec(RoutineLog)], ['query']),
  'getTodaySummary' : IDL.Func([], [DailySummary], ['query']),
  'getTodaysMovementEntries' : IDL.Func(
      [],
      [IDL.Vec(MovementEntry)],
      ['query'],
    ),
  'getTodaysNutritionEntries' : IDL.Func(
      [],
      [IDL.Vec(NutritionEntry)],
      ['query'],
    ),
  'getTodaysSleepEntry' : IDL.Func([], [IDL.Opt(SleepEntry)], ['query']),
  'getTodaysStressEntry' : IDL.Func([], [IDL.Opt(StressEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'startFasting' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'stopFasting' : IDL.Func([IDL.Nat], [], []),
  'toggleRoutineCompletion' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const RoutineLog = IDL.Record({
    'date' : IDL.Text,
    'completed' : IDL.Bool,
    'routineId' : IDL.Nat,
  });
  const DailySummary = IDL.Record({
    'movement' : IDL.Bool,
    'stress' : IDL.Bool,
    'routines' : IDL.Bool,
    'sleep' : IDL.Bool,
    'fasting' : IDL.Bool,
    'nutrition' : IDL.Bool,
  });
  const MovementEntry = IDL.Record({
    'id' : IDL.Nat,
    'activityType' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'intensity' : IDL.Nat,
  });
  const NutritionEntry = IDL.Record({
    'id' : IDL.Nat,
    'fat' : IDL.Nat,
    'carbs' : IDL.Nat,
    'calories' : IDL.Nat,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'protein' : IDL.Nat,
  });
  const SleepEntry = IDL.Record({
    'id' : IDL.Nat,
    'durationHours' : IDL.Float64,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'qualityRating' : IDL.Nat,
  });
  const StressEntry = IDL.Record({
    'id' : IDL.Nat,
    'techniques' : IDL.Text,
    'level' : IDL.Nat,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMovementEntry' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addNutritionEntry' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addRoutine' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'addSleepEntry' : IDL.Func([IDL.Float64, IDL.Nat, IDL.Text], [IDL.Nat], []),
    'addStressEntry' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyScore' : IDL.Func([], [IDL.Nat], ['query']),
    'getTodayRoutineLogs' : IDL.Func([], [IDL.Vec(RoutineLog)], ['query']),
    'getTodaySummary' : IDL.Func([], [DailySummary], ['query']),
    'getTodaysMovementEntries' : IDL.Func(
        [],
        [IDL.Vec(MovementEntry)],
        ['query'],
      ),
    'getTodaysNutritionEntries' : IDL.Func(
        [],
        [IDL.Vec(NutritionEntry)],
        ['query'],
      ),
    'getTodaysSleepEntry' : IDL.Func([], [IDL.Opt(SleepEntry)], ['query']),
    'getTodaysStressEntry' : IDL.Func([], [IDL.Opt(StressEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'startFasting' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'stopFasting' : IDL.Func([IDL.Nat], [], []),
    'toggleRoutineCompletion' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };