/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailySummary {
  'movement' : boolean,
  'stress' : boolean,
  'routines' : boolean,
  'sleep' : boolean,
  'fasting' : boolean,
  'nutrition' : boolean,
}
export interface MovementEntry {
  'id' : bigint,
  'activityType' : string,
  'durationMinutes' : bigint,
  'notes' : string,
  'timestamp' : bigint,
  'intensity' : bigint,
}
export interface NutritionEntry {
  'id' : bigint,
  'fat' : bigint,
  'carbs' : bigint,
  'calories' : bigint,
  'notes' : string,
  'timestamp' : bigint,
  'protein' : bigint,
}
export interface RoutineLog {
  'date' : string,
  'completed' : boolean,
  'routineId' : bigint,
}
export interface SleepEntry {
  'id' : bigint,
  'durationHours' : number,
  'notes' : string,
  'timestamp' : bigint,
  'qualityRating' : bigint,
}
export interface StressEntry {
  'id' : bigint,
  'techniques' : string,
  'level' : bigint,
  'notes' : string,
  'timestamp' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMovementEntry' : ActorMethod<[string, bigint, bigint, string], bigint>,
  'addNutritionEntry' : ActorMethod<
    [bigint, bigint, bigint, bigint, string],
    bigint
  >,
  'addRoutine' : ActorMethod<[string, string], bigint>,
  'addSleepEntry' : ActorMethod<[number, bigint, string], bigint>,
  'addStressEntry' : ActorMethod<[bigint, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyScore' : ActorMethod<[], bigint>,
  'getTodayRoutineLogs' : ActorMethod<[], Array<RoutineLog>>,
  'getTodaySummary' : ActorMethod<[], DailySummary>,
  'getTodaysMovementEntries' : ActorMethod<[], Array<MovementEntry>>,
  'getTodaysNutritionEntries' : ActorMethod<[], Array<NutritionEntry>>,
  'getTodaysSleepEntry' : ActorMethod<[], [] | [SleepEntry]>,
  'getTodaysStressEntry' : ActorMethod<[], [] | [StressEntry]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'startFasting' : ActorMethod<[bigint], bigint>,
  'stopFasting' : ActorMethod<[bigint], undefined>,
  'toggleRoutineCompletion' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];